version: '3'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: management
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yasmin

  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8088:8088"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/management
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: yasmin
